trigger:
- main

pool:
  vmImage: 'windows-latest'
strategy:
  matrix:
    Python36:
      python.version: '3.6'
    Python37:
      python.version: '3.7'
    Python38:
      python.version: '3.8'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    python -m pip install -r requirements/pip.txt
    python -m pip install -r requirements/test.txt
    python -m pip install -r requirements/azurepipes.txt
    pip install --editable .
  displayName: 'Install dependencies'

- script: pytest
  displayName: 'pytest'
